Fix manifest_provider `_get_url_contents()` mocking
In python 2, `test/test_manifest_providers.py`,
`mock_get_url_contents()` needs to decode the mocked `utf-8`-encoded
package XML bytes to simulate more accurately what comes out of
`rosdistro.manifest_provider.github._get_url_contents()`.  8-bit bytes
are thrown into the XML to exercise this behavior.

After this change, the tests fail with the following error:

    ======================================================================
    ERROR: test_manifest_providers.test_github_source
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      [...]
      File "[...]/rosdistro/test/test_manifest_providers.py", line 92, in test_github_source
        repo_cache = rosdistro.manifest_provider.github.github_source_manifest_provider(_genmsg_source_repo())
      File "[...]/rosdistro/src/rosdistro/manifest_provider/github.py", line 122, in github_source_manifest_provider
        name = parse_package_string(package_xml).name
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 540, in parse_package_string
        raise InvalidPackage('The manifest contains invalid XML:\n%s' % ex, filename)
    InvalidPackage: The manifest contains invalid XML:
    'ascii' codec can't encode character u'\xf6' in position 337: ordinal not in range(128)

This commit addresses the "more-information-needed" label added to
PR #133.